name: 'CI-CD Terraform destroy'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm destruction'
        required: true
        default: 'no'

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  terraform_static_analysis:
    name: 'Terraform Static Analysis'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_static_analysis
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Destroy
        working-directory: terraform 
        run: |
          terraform init  
          terraform destroy --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Remove CNAME Record from Route 53
        run: |
          aws route53 change-resource-record-sets \
            --hosted-zone-id $(terraform output -raw route53_zone_id) \
            --change-batch '{
              "Changes": [
                {
                  "Action": "DELETE",
                  "ResourceRecordSet": {
                    "Name": "tm.lab.mohammedsayed.com",
                    "Type": "CNAME",
                    "TTL": 300,
                    "ResourceRecords": [
                      {
                        "Value": "$(terraform output -raw alb_dns_name)"
                      }
                    ]
                  }
                }
              ]
            }'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
